worker_processes auto;
events { worker_connections 4096; }
http {
    client_max_body_size 10G;
    upstream backend { server backend:8000; }
    upstream frontend { server frontend:80; }
    server {
        listen 80;
        location /api/ { proxy_pass http://backend; proxy_buffering off; }
        location / { proxy_pass http://frontend; try_files $uri $uri/ /index.html; }
    }
}
